""" Copyright 2023 Jason Lines.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

"""Type stub file"""

class InvalidLoggingLevelError(Exception): ...
class InvalidServiceDefinitionsExceptionError(Exception): ...
class CrawlerNotFoundExecptionError(Exception): ...
class MetadataClassNotFoundExecptionError(Exception): ...
class PaginatorNotFoundExecptionError(Exception): ...
class EvaluationModuleNotFoundExecptionError(Exception): ...
class EvaluationModuleFailedToLoadExecptionError(Exception): ...
class EvaluationMethodNotFoundError(Exception): ...
class EvaluationMethodNameError(Exception): ...
class EvaluationMethodResultOutputError(Exception): ...
class ActiveCrawlerScanExceptionError(Exception): ...
class FailedCrawlerScanExceptionError(Exception): ...
class TimeOutCrawlerScanExceptionError(Exception): ...
class CrawlerScanUnexpectedDataExceptionError(Exception): ...