"""Type stub file"""

from typing import Any

WHITEBOARD: Whiteboard

class Whiteboard:
    board: dict[str, Any]

    def __init__(self) -> None: ...
    def new_section(self, section: str) -> None: ...
    def get_section(self, section: str) -> dict[str, Any]: ...
    def remove_section(self, section: str) -> None: ...
    def write(
        self,
        section: str,
        title: str,
        msg: Any,
        signature: str = ...,
        overwrite: bool = ...,
    ) -> None: ...
    def get(
        self, section: str, title: str = ..., signature: str = ...
    ) -> list[Any]: ...
    def erase(self, section: str, title: str = ..., signature: str = ...) -> None: ...
    def scribble(self, title: str, msg: Any) -> None: ...
    def get_scribble(self, title: str) -> Any: ...
    def print(self) -> None: ...
